[application]
name = "gul-website"
default_platform = "web"

[web.app]
title = "GUL - The Universal Programming Language"
base_path = "/"

[web.watcher]
watch_path = ["src", "public"]
reload_html = true
index_on_404 = true

[web.resource]
style = ["/style.css"]

[web.resource.dev]
style = ["/style.css"]
